[package]
name = "gogextract"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
indicatif = "0.17"
regex = "1.10"
flate2 = "1.0"
tar = "0.4"
zip = "0.6"
ctrlc = "3.4"
memmap2 = "0.9"
rayon = "1.8"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
